---
- name: install nginx
  hosts: web
  become: yes

  tasks:
    - name: Ensure nginx package is present
      apt:
       name: nginx
       state: present
    - name: Ensure index.html present in directory
      copy:
        src: index.html
        dest: /var/www/index.html
    - name: Ensure nginx service is started
      service:
        name: nginx
        state: started

- name: install db
  hosts: db
  become: yes

  tasks:
    - name: Ensure postgresql installed
      apt:
        name: postgresql
        state: present
    - name: Ensure postgresql is started
      service:
        name: postgresql
        state: started
