version: '2'
services:
  dev:
    build: DevCustom
    ports:
      - "81:8080"
    volumes:
      - /usr/local/tomcat/webapps/
  prod:
    image: tomcat:8.0-slim
    depends_on:
      - dev
    ports:
      - "80:8080"
    volumes_from:
      - dev